//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookOnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;


    public partial class User
    {
        public int id { get; set; }

        [DisplayName("User Name")]
        [Required(ErrorMessage = "Error User Name")]
        public string username { get; set; }

        [DisplayName("Password")]
        [Required]
        [StringLength(100,ErrorMessage = "Password can lenght > 6",MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [Display(Name = "Comfirm Password")]
        [DataType(DataType.Password)]
        [System.Web.Mvc.Compare("password",ErrorMessage = "Password not macth")]
        public string comfirmPassword { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Error email")]
        public string email { get; set; }

        [DisplayName("Address")]
        [Required(ErrorMessage = "Address Error")]
        public string address { get; set; }

        [DisplayName("Phone Number")]
        [Required(ErrorMessage = "Phone not null")]
        public string phone { get; set; }

        [DisplayName("Photo")]
        public string photo { get; set; }
    }
}
